
package net.webservicex;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10-b140319.1121
 * Generated source version: 2.2
 *
 */
@WebService(name = "lengthUnitSoap", targetNamespace = "http://www.webserviceX.NET/")
@XmlSeeAlso({ ObjectFactory.class })
public interface LengthUnitSoap {


    /**
     *
     * @param lengthValue
     * @param toLengthUnit
     * @param fromLengthUnit
     * @return
     *     returns double
     */
    @WebMethod(operationName = "ChangeLengthUnit", action = "http://www.webserviceX.NET/ChangeLengthUnit")
    @WebResult(name = "ChangeLengthUnitResult", targetNamespace = "http://www.webserviceX.NET/")
    @RequestWrapper(localName = "ChangeLengthUnit", targetNamespace = "http://www.webserviceX.NET/",
                    className = "net.webservicex.ChangeLengthUnit")
    @ResponseWrapper(localName = "ChangeLengthUnitResponse", targetNamespace = "http://www.webserviceX.NET/",
                     className = "net.webservicex.ChangeLengthUnitResponse")
    public double changeLengthUnit(@WebParam(name = "LengthValue", targetNamespace = "http://www.webserviceX.NET/")
                                   double lengthValue,
                                   @WebParam(name = "fromLengthUnit", targetNamespace = "http://www.webserviceX.NET/")
                                   Lengths fromLengthUnit,
                                   @WebParam(name = "toLengthUnit", targetNamespace = "http://www.webserviceX.NET/")
                                   Lengths toLengthUnit);

}
